spring.application.name=app
server.port=8090

spring.datasource.url=jdbc:mysql://localhost:3306/dbtravel
 #?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=12345678
spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true


# 1. Configuración del Cliente (OAuth2 Login)
spring.security.oauth2.client.registration.keycloak.client-id=travel-backend
spring.security.oauth2.client.registration.keycloak.client-secret=UD4BhZsGWX8AVOS41CqL8FwaSGGsZYjI
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/keycloak

# 2. Configuración del Provider (Sacado de tu JSON)
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:9090/realms/travel-realm

# 3. Configuración del Resource Server (Para validar JWT)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/travel-realm
